data0.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data1.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data2.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data3.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data4.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data5.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data6.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data7.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data8.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data9.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data10.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data11.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data12.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data13.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data14.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data15.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data16.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data17.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 2
  subtaskId: 1
  isPretest: false
data18.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 32
  subtaskId: 2
  isPretest: false
data19.in:
  timeLimit: 1000
  memoryLimit: 64000
  score: 32
  subtaskId: 2
  isPretest: false