data0.in:
  timeLimit: 500
  memoryLimit: 1
data1.in:
  timeLimit: 500
  memoryLimit: 1
data2.in:
  timeLimit: 500
  memoryLimit: 1
data3.in:
  timeLimit: 500
  memoryLimit: 1
data4.in:
  timeLimit: 500
  memoryLimit: 1
data5.in:
  timeLimit: 500
  memoryLimit: 1
data6.in:
  timeLimit: 500
  memoryLimit: 1
data7.in:
  timeLimit: 500
  memoryLimit: 1
data8.in:
  timeLimit: 500
  memoryLimit: 1
data9.in:
  timeLimit: 500
  memoryLimit: 1
data10.in:
  timeLimit: 500
  memoryLimit: 1
data11.in:
  timeLimit: 500
  memoryLimit: 1
data12.in:
  timeLimit: 500
  memoryLimit: 1
data13.in:
  timeLimit: 500
  memoryLimit: 1
data14.in:
  timeLimit: 500
  memoryLimit: 1
data15.in:
  timeLimit: 500
  memoryLimit: 1
data16.in:
  timeLimit: 500
  memoryLimit: 1
data17.in:
  timeLimit: 500
  memoryLimit: 1
data18.in:
  timeLimit: 500
  memoryLimit: 1
data19.in:
  timeLimit: 500
  memoryLimit: 1
